### ISSUE TITLE
Create /invite and adapt /moderation && /projects …

### ISSUE THREAD

**Issue by andirueckel** [medienhaus/medienhaus-cms#100]
- [ ] `/invite` route should show anything related to invites, i.e. collaboration/moderation invitations and invite function
- [ ] rename `/moderation` to `/moderate`
- [ ] `/moderate` route should show anything related to moderation, i.e. contexts, requests, and promotion function
- [ ] remove invitations from `/projects`
- [ ] add notifications icon for `/invite`
- [ ] check notifications for `/moderate`

**Comment by marcel-klasse** [comment]
partially implemented
