### ISSUE TITLE
Improve context menu / dropdown

### ISSUE THREAD

**Issue by andirueckel** [medienhaus/medienhaus-cms#101]
In addition to https://github.com/medienhaus/medienhaus-cms/issues/51, list requested context below context menu accompanied by cancel request `<button>`.

Also, how about closing/collapsing the context menu after successfully having requested one context?

**Comment by fnwbr** [comment]
Listing requested contexts is currently tricky because we can't ask the Matrix API to "give us all the contexts we have knocked on".

Instead we have to loop through -all- of the contexts and check for every single one if we have knocked on them.

**Comment by fnwbr** [comment]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/706419/135294580-bc85c822-ead0-4e3e-900a-18137e13f781.png">

**Comment by fooness** [comment]
`1.` — We don’t do that.

**Comment by andirueckel** [comment]
1. — We don’t do that.
