### ISSUE TITLE
Allow to /create events (without context), and add /events route

### ISSUE THREAD

**Issue by andirueckel** [medienhaus/medienhaus-cms#105]
On `/create`, choose wether to create a project or an event; projects don’t need any change, yet, but events don’t need context. This could be achieved by either contextualizing all events by e.g. “Rundgang $YYYY”, or by only showing faculty, institute, or study program, class(?), and the additionally-to-be-created contexts from the `.docx`, but no courses, seminars, workshops, et cetera … the latter option would unfortunately turn out to be complicated rather quickly?

Another approach would be simply filtering out all contexts of `type === course` (which might include classes), or to provisionally change the publishing criteria to context not required; which might introduce other problems?

**Comment by fnwbr** [comment]
Alternative:

- Rename `/projects` to `/content`
- Introduce the concept of a "content type"
    - Define those content types in some sort of config file
    - Also allow disabling/pre-populating certain UI parts via that config file
        - e.g. `type === event` should not show the context dropdown, but instead put all events in a predefined space/context
        - e.g. `type === static` should not show the context dropdown nor the new "events/venue" component but only the text "content" 
- Introduce a "content type" dropdown on `/create`
    - Which would then allow selecting between the defined types like: `studentproject`/`event`

**Comment by andirueckel** [comment]
Let’s manage `type === context` the same way, and allow respective moderators to access the content editor to create and manage the context information page (description, text, images, et cetera) this way?
