### ISSUE TITLE
`Show Preview` button does not open preview in `target="_blank"` …

### ISSUE THREAD

**Issue by andirueckel** [medienhaus/medienhaus-cms#110]
Needs fix: https://github.com/medienhaus/medienhaus-cms/blob/main/src/routes/create/index.js#L303

**Comment by marcel-klasse** [comment]
afaik `target="_blank` won't work with internal routing. would probably have to be a normal url.

**Comment by andirueckel** [comment]
Alternatively we could add a `Back to Edit` button below the preview frame, maybe.

To be discussed, not urgent.
