### ISSUE TITLE
Show avatar in proper resolution in /account (via support)

### ISSUE THREAD

**Issue by andirueckel** [medienhaus/medienhaus-cms#120]
In `/account`, don’t use the avatar’s thumbnail URL and/or don’t crop the image.

https://github.com/medienhaus/medienhaus-cms/blob/493c85e8929c85e865a30d24d854614efe3afd7c/src/routes/account/Avatar/avatar.js#L15

**Comment by fnwbr** [comment]
I assume just `matrixClient.mxcUrlToHttp(currentAvatar)` will return the full-resolution URL for the avatar; so not the one for the cropped thumbnail. Should be easy to test in a local dev environment.
