### ISSUE TITLE
Rundgang-specific instructions need adjustment for Gutenberg

### ISSUE THREAD

**Issue by fnwbr** [medienhaus/medienhaus-cms#161]
Some of this doesn't make sense or is not accurate anymore:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/706419/174097671-c3a2849a-598a-4352-9e81-ae88ce7ccc9a.png">

**Comment by andirueckel** [comment]
Let’s keep the obsolete text in a pad as a reference, and let’s ask *marketing* on Monday, pre-launch, to adapt the text for the new editor in both `en` and `de` locales; we’ll implement the text changes before going live …

**Comment by fnwbr** [comment]
Don't need to "keep references" as they're all in the git history. I think we can make the changes ourselves also; no need to do another circle with marketing.
