### ISSUE TITLE
`/create` location select: buildings and floors should not be selectable

### ISSUE THREAD

**Issue by andirueckel** [medienhaus/medienhaus-cms#165]
<img width="720" alt="Screen Shot 2022-06-17 at 16 10 38" src="https://user-images.githubusercontent.com/63073125/174315148-9e7869b0-0403-4c6c-91a4-1e868bce7363.png">

**Comment by andirueckel** [comment]
Might or might not be related to: https://github.com/medienhaus/medienhaus-cms/issues/160

**Comment by fnwbr** [comment]
Looks like it was fixed
