### ISSUE TITLE
Collaboration broken with Gutenberg editor

### ISSUE THREAD

**Issue by marcel-klasse** [medienhaus/medienhaus-cms#171]
- Edits by collaborators are only visible after reloading.
- collaborators are not invited to newly created content rooms, therefore can't edit content they didn't create themselves
![image](https://user-images.githubusercontent.com/79279756/174437002-d74e70f1-83b0-400b-b518-25903509f4ea.png)

**Comment by marcel-klasse** [comment]
fixed with #172

**Comment by fnwbr** [comment]
Thanks a lot!
