### ISSUE TITLE
`/moderate` short description textarea: “fast” text input results in massive performance issues

### ISSUE THREAD

**Issue by andirueckel** [medienhaus/medienhaus-cms#179]
reproduce: type some text rather fast and then … wait for it

maybe relevant: https://github.com/medienhaus/medienhaus-cms/commit/3869508c101d239df1536cc629a95e3daecaa9bc

<img width="1552" alt="Screen Shot 2022-06-22 at 10 29 16" src="https://user-images.githubusercontent.com/63073125/174982184-d1d10ba9-6670-4456-841a-dfcac267a4b3.png">

**Comment by marcel-klasse** [comment]
fixed with 598cd0114f54272d75588ea85df4bcc905ed6766
