### ISSUE TITLE
Audio Content is not displayed in gutenberg after uploading

### ISSUE THREAD

**Issue by robertschnuell** [medienhaus/medienhaus-cms#203]
While the upload process works for audio files, still it is not rendered after uploading into an audio html element, as it is before clicking 'saving changes' and starting the upload process. however it seems as the file got uploaded sucessfully, so it is just an inferface bug, which renders an upload button instead of the html audio element into the gutenberg editor after uploading.

**Comment by robertschnuell** [comment]
problem found, and fix implemented is described in this branch: https://github.com/medienhaus/medienhaus-cms/tree/gutenberg-image-audio-and-file-upload-fix

**Comment by marcel-klasse** [comment]
fixed in #204
