### ISSUE TITLE
`/create` context list should not be displayed if empty

### ISSUE THREAD

**Issue by andirueckel** [medienhaus/medienhaus-cms#208]
https://github.com/medienhaus/medienhaus-cms/blob/udk-update/src/routes/create/Category/index.js#L222-L231

<img width="1092" alt="Screenshot 2023-06-21 at 14 35 18" src="https://github.com/medienhaus/medienhaus-cms/assets/63073125/50ac3fab-7fae-4757-a966-b407579472b8">

<img width="1136" alt="Screenshot 2023-06-21 at 14 35 20" src="https://github.com/medienhaus/medienhaus-cms/assets/63073125/ce7835e1-8cc6-4f94-87c2-ee4b41093fbc">

**Comment by marcel-klasse** [comment]
fixed in 7e398fbb8ca12efa4856c05e1b7b735054841a6b
