### ISSUE TITLE
Change content language dropdown to a different UI

### ISSUE THREAD

**Issue by fnwbr** [medienhaus/medienhaus-cms#72]
Mögliche Verbesserung bei der Sprachauswahl für die Projektbeschreibung: Vielleicht eine art Tab-/Registerkarten-UI, statt des Dropdowns. Im Moment wird suggeriert, dass nur eine Sprache wirklich unterstützt und auch gespeichert wird.

**Comment by andirueckel** [comment]
Maybe wouldn’t be accurate compared to the final website design, but the language chooser would be more intuitive and logical **inside** the preview iframe. Let’s ask @Franz-Kafka to add the chooser to the upper right corner of the preview frame in the respective design, i.e. white text on black pill?
