### ISSUE TITLE
Invitations to a random space show up as "invitation to collaborate"

### ISSUE THREAD

**Issue by fnwbr** [medienhaus/medienhaus-cms#85]
![image](https://user-images.githubusercontent.com/706419/133653074-0dc26d65-51e6-4349-b0c5-c84cd729498f.png)

In this case `Tonsatz/Gehörbildung BA LA Musik Grundschule Kurs 1` is obviously not a project, but an invitation to just a random Matrix space. (In this specific case a "context" space actually.)

We should add a check if the space that the invitation is for is actually for... a project space? But... can we do that before being able to look inside the space?

**Comment by fnwbr** [comment]
We can also say: Since we're on a separate Matrix server there will never be any "random" spaces, except for:

- context spaces, or
- project spaces

And given that for the former you can't really accidentally invite someone, but the users have to knock first... we can maybe just ignore this.

But in that case this is another argument for a whole separate Matrix server. (As we have implemented for the moment.)

**Comment by marcel-klasse** [comment]
we can just edit the text to be less specific about invations or include that invitations to context spaces also show up here.
Maybe it also makes sense put invites within account . 
Woud veto a seperate nav element for invites as it's getting quite large

**Comment by marcel-klasse** [comment]
> We can also say: Since we're on a separate Matrix server there will never be any "random" spaces, except for:
> 
>     * context spaces, or
> 
>     * project spaces
> 
> 
> And given that for the former you can't really accidentally invite someone, but the users have to knock first... we can maybe just ignore this.
> 
> But in that case this is another argument for a whole separate Matrix server. (As we have implemented for the moment.)

I think as you say atm its not a big issue. In the future[medienhaus/ frontend]( https://github.com/medienhaus/medienhaus-frontend) will probably be used for invites etc.

So for now I think moving it/ changing the description or sth similar is enough.
