### ISSUE TITLE
Replace Date and Time with Event category

### ISSUE THREAD

**Issue by marcel-klasse** [medienhaus/medienhaus-cms#98]
bundle location and time into new event category

**Comment by andirueckel** [comment]
Would be good to be able to `+ ADD EVENT` and then be able to optionally enter date, time, and venue in their respective elements, i.e. `<input>` for date and time, and `<select>` for venue; additionally show two `<button>` elements to cancel or save via surrounding `<div class="confirmation">`; once added, display new/second `<button>+ ADD EVENT</button>` …

Edit could be possible similar to project title; when focused and changed, show two `<button>` elements to cancel or save via surrounding `<div class="confirmation">`; additionally show `<button> `to delete event.

**Comment by marcel-klasse** [comment]
> Would be good to be able to `+ ADD EVENT` and then be able to optionally enter date, time, and venue in their respective elements, i.e. `<input>` for date and time, and `<select>` for venue; additionally show two `<button>` elements to cancel or save via surrounding `<div class="confirmation">`; once added, display new/second `<button>+ ADD EVENT</button>` …
> 
> Edit could be possible similar to project title; when focused and changed, show two `<button>` elements to cancel or save via surrounding `<div class="confirmation">`; additionally show `<button> `to delete event.

not sure what you mean but isn't that exctly how it is atm?

**Comment by andirueckel** [comment]
> not sure what you mean but isn't that exctly how it is atm?

In `branch:events`? Looks good. Let me know once adding works, then I’ll re-evaluate …
